In [3]:
import pandas as pd

# Load all CSV files into DataFrames
courses = pd.read_csv('courses.csv')
assessments = pd.read_csv('assessments.csv')
vle = pd.read_csv('vle.csv')
student_info = pd.read_csv('studentInfo.csv')
student_registration = pd.read_csv('studentRegistration.csv')
student_assessment = pd.read_csv('studentAssessment.csv')
student_vle = pd.read_csv('studentVle.csv')

In [4]:
# Display columns of each DataFrame
print("Courses columns:", courses.columns)
print("Assessments columns:", assessments.columns)
print("VLE columns:", vle.columns)
print("Student Info columns:", student_info.columns)
print("Student Registration columns:", student_registration.columns)
print("Student Assessment columns:", student_assessment.columns)
print("Student VLE columns:", student_vle.columns)

Courses columns: Index(['code_module', 'code_presentation', 'module_presentation_length'], dtype='object')
Assessments columns: Index(['code_module', 'code_presentation', 'id_assessment', 'assessment_type',
       'date', 'weight'],
      dtype='object')
VLE columns: Index(['id_site', 'code_module', 'code_presentation', 'activity_type',
       'week_from', 'week_to'],
      dtype='object')
Student Info columns: Index(['code_module', 'code_presentation', 'id_student', 'gender', 'region',
       'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts',
       'studied_credits', 'disability', 'final_result'],
      dtype='object')
Student Registration columns: Index(['code_module', 'code_presentation', 'id_student', 'date_registration',
       'date_unregistration'],
      dtype='object')
Student Assessment columns: Index(['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score'], dtype='object')
Student VLE columns: Index(['code_module', 'code_presentation', 'id_student', 'id_site', 'date',
       'sum_click'],
      dtype='object')

In [5]:
# Merge student_info with student_assessment
student_info_assessment = pd.merge(student_info, student_assessment, on='id_student')

# Merge the result with assessments to get the assessment details
#student_info_assessment = pd.merge(student_info_assessment, assessments, on='id_assessment')

# Merge student_info_assessment with student_vle to include VLE interactions
#student_data = pd.merge(student_info_assessment, student_vle, on=['id_student', 'code_module', 'code_presentation'], how='left')

In [6]:
student_info_assessment = pd.merge(student_info_assessment, assessments, on='id_assessment')

In [8]:
student_data = pd.merge(student_info_assessment, student_vle, on='code_module')

KeyError: 'code_module'

In [9]:
student_info_assessment.head()

,code_module_x,code_presentation_x,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,final_result,id_assessment,date_submitted,is_banked,score,code_module_y,code_presentation_y,assessment_type,date,weight
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,Pass,1752,18,0,78.0,AAA,2013J,TMA,19.0,10.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,Pass,1752,22,0,70.0,AAA,2013J,TMA,19.0,10.0
2,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,Pass,1752,17,0,72.0,AAA,2013J,TMA,19.0,10.0
3,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,Pass,1752,26,0,69.0,AAA,2013J,TMA,19.0,10.0
4,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,...,Pass,1752,19,0,79.0,AAA,2013J,TMA,19.0,10.0

In [13]:
student_vle.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [6]:
import pandas as pd

# Load all CSV files into DataFrames
courses = pd.read_csv('courses.csv')
assessments = pd.read_csv('assessments.csv')
vle = pd.read_csv('vle.csv')
student_info = pd.read_csv('studentInfo.csv')
student_registration = pd.read_csv('studentRegistration.csv')
student_assessment = pd.read_csv('studentAssessment.csv')
student_vle = pd.read_csv('studentVle.csv')

# Merge student_info with student_assessment
student_info_assessment = pd.merge(student_info, student_assessment, on='id_student', how='left')
student_info_assessment = pd.merge(student_info_assessment, assessments, on='id_assessment')
# Drop duplicate columns
student_info_assessment = student_info_assessment.drop(['code_module_y', 'code_presentation_y'], axis=1)
student_info_assessment.rename(columns={'code_module_x': 'code_module', 'code_presentation_x': 'code_presentation'}, inplace=True)

# Merge the result with assessments to get the assessment details
#student_info_assessment = pd.merge(student_info_assessment, assessments, on='id_assessment', how='left')

# Merge student_info_assessment with student_vle to include VLE interactions
#student_data = pd.merge(student_info_assessment, student_vle, on=['id_student', 'code_module', 'code_presentation'], how='left')

# Continue with the rest of the analysis...

In [8]:
student_data = pd.merge(student_info_assessment, student_vle, on='id_student', how='left')

KeyboardInterrupt:

In [11]:
student_info_assessment.shape[0]

207319

In [12]:
# Number of unique id_student in student_info_assessment
unique_students_info_assessment = student_info_assessment['id_student'].nunique()
print(f'Unique id_student in student_info_assessment: {unique_students_info_assessment}')

# Number of unique id_student in student_vle
unique_students_vle = student_vle['id_student'].nunique()
print(f'Unique id_student in student_vle: {unique_students_vle}')

Unique id_student in student_info_assessment: 23369
Unique id_student in student_vle: 26074